LEFTBUTTON = 1
FPS = 60
SHIPAY = 5 / 6
CUBEAY = 5 / 6
WIDTH = 1500
HEIGHT = 1500 / 16 * 9
SHIP_WAVE_CEIL = HEIGHT - 100 - 64*10
SPEED = 480
STATUS = None
GAMESPEED = None
STARTPOSITION = HEIGHT - 150
GAMESTARTED = None
MAXSPEED = 1000/60


def init_variables():
    global STATUS
    global GAMESTARTED
    global GAMESPEED
    STATUS = 'MAIN'
    GAMESTARTED = False
    GAMESPEED = 1
